# Generated by Django 5.2.6 on 2025-09-29 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('car_number', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('man_date', models.DateField()),
                ('email', models.EmailField(max_length=254)),
                ('Type', models.CharField(max_length=10)),
            ],
        ),
    ]
